---
title: "Foundations of ecological and evolutionary change"
author: |
  | A. Bradley Duthie$^{1,a,*}$ and Victor J. Luque$^{2,a}$
date: '[1] Department of Biological and Environmental Sciences, University of Stirling, Stirling, Scotland [2] Department of Philosophy, University of Valencia, Valencia, Spain [*] Corresponding author: alexander.duthie@stir.ac.uk [a] Equal contribution'
output:
  pdf_document:
      keep_tex: yes
  word_document: default
  html_document:
    df_print: paged
header-includes:
- \usepackage{fancyhdr}
- \usepackage{lineno}
linestretch: 1
bibliography: refs.bib
link-citations: yes
linkcolor: blue
csl: the-american-naturalist.csl
biblio-style: apalike
---



Abstract
=====================================

Biological evolution is realised through the same mechanisms of birth and death that underlie change in population density. 
The deep interdependence between ecology and evolution is well-established, and recent models focus on integrating eco-evolutionary dynamics to demonstrate how ecological and evolutionary processes interact and feed back upon each other. 
Nevertheless, a gap remains between the logical foundations of ecology and evolution. 
Both population ecology and evolution have fundamental equations that define how the size of a population (ecology) and the average characteristic within a population (evolution) change, respectively, over time.
These fundamental equations are a complete and exact description of change for any closed population, but how they are formally linked remains unclear.
We link the fundamental equations of population ecology and evolution with an equation that sums how individual characteristics interact with individual fitness in a population.
From this equation, we derive the fundamental equations of population ecology and evolutionary biology (the Price equation). 
We thereby identify an overlooked bridge between ecology and biological evolution. 
Our unification formally recovers the equivalence between mean population growth rate and evolutionary fitness and links this change to ecosystem function. 
We outline how our framework can be used to further develop eco-evolutionary theory. 

**Key words:** Ecology, Evolution, Eco-Evolutionary Theory, Fundamental Theorem, Price Equation, Population Growth

<!---

Non-technical Summary
=====================================

Biologists have long known that the ecology of population size is inextricably linked with the evolution of population traits. Nevertheless, foundational theories underlying ecological and evolutionary change have been historically separated, with recent attempts to bridge the theoretical divide using eco-evolutionary modelling. We discover a new equation from first principles that provides a universal and complete definition for eco-evolutionary change. This equation thereby offers a unified framework for ecology and evolution, which also recovers the foundational theory of ecology and evolution as developed in isolation. 

--->

Introduction
=====================================

Theoretical unification is a powerful tool for scientific advancement.
Such unification has been a major goal in scientific research throughout history [@Smocovitis1992; @Kitcher1993], and its value is perhaps most evident in reconciling unconnected models and revealing new and unexpected empirical predictions. 
In evolutionary biology, the Price equation (Box 1) provides a unifying framework for evolutionary theory by exhaustively and exactly describing evolutionary change for any closed evolving population [@Price1970; @Luque2016; @Lehtonen2020].
The Price equation is therefore fundamental, in the sense that it binds together all of evolutionary theory by formally defining what evolutionary change is and is not [@Price1970; @Rice2004; @Gardner2008; @Frank2015a; @Luque2016; @Luque2021].
Using this formal definition, the scope of, and relationships among, sub-disciplines within evolutionary theory can be clarified.
For example, fundamental equations of both population and quantitative genetics can be derived from the Price equation [@Queller2017].
This provides conceptual clarity by demonstrating the logical consistency of different theoretical frameworks within evolutionary biology.
Our aim here is to propose an equation that extends this conceptual clarity to include population size change and thereby provide a formal and exact definition for joint ecological and evolutionary change.

In biological populations, ecological change is caused by the same processes of individual birth and death that cause evolutionary changes in allele frequencies and phenotypes [@Turchin2001; @Connor2004; @Barfield2011].
As with evolution, a fundamental equation can exhaustively and exactly define population change.
Unlike the Price equation, this fundamental equation is perhaps self-evident. Population change is simply the addition of individuals minus the removal of individuals from current population size ($N_{t}$), which recovers the new population size ($N_{t+1}$; Box 2).
By definition, this relationship of $N_{t+1} = N_{t} + Births - Deaths$ applies to any closed population.
@Turchin2001 argues that general principles are needed to establish a logical foundation for population ecology, and this simple birth and death model and the consequences that logically follow from it (e.g., exponential population growth) are fundamental to population ecology.
Any unifying definition of joint ecological and evolutionary change must be able to derive both the Price equation and this birth and death model.

The union of ecological and evolutionary processes has long been recognised [e.g., @Darwin1859; @Fisher1958; @Pelletier2009], but the rise of eco-evolutionary models, which incorporate both, is relatively recent following a widespread recognition that ecology and evolution can happen on similar timescales [@Govaert2019; @Yamamichi2023].
Currently, a universally recognised formal definition of eco-evolutionary change is lacking, with some theoreticians broadly interpreting "eco-evolutionary dynamics" to allow for a separation of ecological and evolutionary timescales [@Lion2023] and others advocating for a more narrow interpretation in which no such separation is permitted [@Bassar2021].
@Bassar2021 identify two types of eco-evolutionary models that follow from these interpretations.
The first type uses separate equations to model population size change versus evolutionary change, thereby allowing for any number of ecological, evolutionary, or environmental feedbacks [e.g., @Lion2018; @Patel2018; @Lion2023].
The second type models population demographics as functions of quantitative traits with ecological and evolutionary change following from demographic processes and trait distributions operating on the same timescale [e.g., @Barfield2011; @Simmonds2020; @Jaggi2024]. 
Both model types can be very general, but like all predictive models, they rely on simplifying assumptions for tractability [@Levins1966; @Luque2016].
These simplifying assumptions are often grounded in the Price equation to demonstrate accuracy and logical consistency when modelling evolutionary change [e.g., @Coulson2008; @Barfield2011; @Rees2016; @Lion2018].
For example, @Barfield2011 link their model back to @Price1970, which they consider to be a "universal law of evolution", to place their conclusions concerning stage structured evolution in the broader context of evolutionary theory. 
The role of fundamental equations is therefore important for unifying theory [@Luque2021], and we believe that a fundamental equation of eco-evolutionary change has been curiously overlooked.

We present an equation from which the fundamental equations of ecology and evolutionary biology can be derived.
Derivation follows by adding assumptions that are specific to population ecology or evolution in the same way that key equations of population genetics or quantitative genetics can be derived from the Price equation by restricting the domain of interest [e.g., to allele frequencies in the case of population genetics, or to continuous phenotypes in the case of quantitative genetics, @Queller2017].
We propose our equation as a formal definition of eco-evolutionary change.


*******************

> **Box 1:** The Price equation is an abstract formula to represent evolutionary change. Formulated originally in the early 1970s by George Price [@Price1970; @Price1972], it postulates some basic properties that all evolutionary systems must satisfy: change over time, ancestor and descendant relations, and a character or phenotype [@Rice2004]. Using simple algebraic language, the Price equation represents evolutionary change with the predominant notation, $$\bar{w}\Delta\bar{z} = \mathrm{Cov}\left(w, z\right) + \mathrm{E}\left(w\Delta z\right).$$ In the above equation, $\Delta\bar{z}$ is the change in the average character value $z$ over a time step of arbitrary length, $w$ is an individual's fitness, and $\bar{w}$ average population fitness. On the right-hand side of the equation, the first term is the covariance between a character value $z$ and fitness $w$, which reflects $\bar{z}$ change attributable to differential survival and reproduction. The second term is the expected value of $\Delta z$, which reflects the extent to which offspring deviate from parents in $z$ [@Rice2004; @Okasha2006; @Frank2012]. A more specific version of the covariance term was already known within the quantitative and population genetics tradition [@Robertson1966], usually representing the action of natural selection. The Price equation adds an expectation term and abstracts away from any specific mechanisms of replication or reproduction, or mechanisms of inheritance. Its definitional nature and lack of substantive biological assumptions has been portrayed both as a strength [@Rice2004; @Frank2012; @Luque2016; @Baravalle2022], and its greatest weakness. The abstract nature of the Price equation places it at the top of the hierarchy of fundamental theorems of evolution from which the rest (Robertson's theorem, Fisher's fundamental theorem, breeder's equation, Hamilton's rule, adaptive dynamics, etc.) can be derived [@Queller2017; @Lehtonen2016; @Lehtonen2018; @Lehtonen2020a]. This abstractness is also key to developing a more general view of evolution [@Rice2020; @Luque2021; @Edelaar2023]. In contrast, some researchers consider the Price equation just a triviality (even tautological), and useless without further modelling assumptions [@VanVeelen2005; @VanVeelen2012]. The debate remains open [@VanVeelen2020; @Baravalle2024].


*******************


*******************

> **Box 2:** The number of individuals in any closed population ($N$) at any given time ($t + 1$) is determined by the number of individuals at $t$ ($N_{t}$), plus the number of births ($Births$) minus the number of deaths ($Deaths$), $$N_{t+1} = N_{t} + Births - Deaths.$$ This equation is necessarily true for any closed population. Despite its simplicity, it is a general equation for defining population change and a starting point for understanding population ecology. @Turchin2001 notes that a consequence of this fundamental equation is the tendency for populations to grow exponentially (technically geometrically in the above case where time is discrete). This inherent underlying tendency towards exponential growth persists even as the complexities of real populations, such as structure, stochasticity, or density-dependent effects are added to population models [@Turchin2001]. Given the assumption that all individuals in the population are identical, a per capita rate of birth, $Births = bN_{t}$, and death, $Deaths = dN_{t}$, can be defined. Rearranging and defining $\lambda = 1 + b - d$ gives, $N_{t+1} = N_{t}\lambda$. Here $\lambda$ is the finite rate of increase [@Gotelli2001], and note that because $0 \leq d \leq 1$, $\lambda \geq 0$. Verbally, the change in size of any closed population equals its existing size times its finite rate of increase.

*******************


A foundation for biological evolution and population ecology
====================================================

To unify biological evolution and population ecology, we must reconcile the Price equation (Box 1) with the general equation for population change (Box 2).
The Price equation is critical for partitioning different components of biological change [@Price1970; @Frank1997; @Gardner2008; @Luque2016; @Lehtonen2018; @Lehtonen2020a; @Queller2017].
It has also been highly useful for integrating evolutionary theory across disciplines [@Fox2006; @Brantingham2007; @MacCallum2012; @Frank2015; @Godsoe2021; @Ulrich2024].
These properties would seem to make it an intuitive starting point for a logical foundation of ecology and evolution, perhaps through some kind of mathematical equivalence [@Page2002] or addition of terms [@Collins2009], or through the use of its recursive structure [@Kerr2009; @Frank2012].
But despite its flexibility, the Price equation still relies on relative frequencies, which must by definition sum to one [@Frank2015].
This is because the Price equation describes the average change in a population; the frequency of entities is scaled thereby conserving total probability [@Frank2015; @Frank2016].
But to recover the fundamental principle of exponential population growth [@Turchin2001], this scaling must be avoided.

<!---

Previous theory has produced mathematical synthesis between ecological and evolutionary equations [@Page2002; @Collins2009], but not established a unified conceptual framework for joint ecological and evolutionary change.
For example, @Page2002 demonstrate a mathematical equivalence between the Price equation and a general equation for community dynamics. 
In both equations, the relative frequencies of different ecological (species) or evolutionary (phenotype) variants map to their respective ecological (population growth) or evolutionary (fitness) change in a way that is mathematically equivalent.
@Collins2009 use the Price equation to build a general quantitative framework that partitions phenotypic change into ecological, evolutionary, and physiological components.
The average change in a community-wide trait (e.g., carbon uptake) is exactly and generally partitioned into change attributable to changes in species composition, expected evolution of lineages within species, and expected change in lineage physiology across all species.
Both @Page2002 and @Collins2009 use relative species abundances, meaning that species frequencies must sum to one.
This is useful for demonstrating mathematical equivalence [@Page2002] or expected change in a community-wide trait [@Collins2009], but a different approach is needed to recover absolute change in population size and thereby recover a joint foundation for ecology and evolution.


--->


We therefore begin with the most fundamental axioms underlying the ecology and evolution of living systems [@Rice2004; @Rice2009].
In such systems, diversity is discontinuous, in the sense that living systems are composed of discrete entities including individual organisms and groups of organisms [@Dobzhansky1970].
Our framework is general enough that entities can be anything discrete, but we will focus on each entity $i$ as an individual organism.
Individuals give rise to new individuals through birth such that $\beta_{i}$ is the number of births attributable to $i$.
Individuals are removed from the population through death such that $\delta_{i}$ is an indicator variable that takes a value of 1 (death of $i$) or 0 (persistence of $i$).
All individuals are defined by some characteristic $z_{i}$, and $\Delta z_{i}$ defines any change in $z_{i}$ from one time step $t$ to the next $t + 1$.
The total number of individuals in the population is $N$.
From this foundation, we can define $\Omega$ to be a summed characteristic across $N$ entities,

$$\Omega = \sum_{i=1}^{N} \left(\beta_{i} - \delta_{i} + 1 \right)\left(z_{i} + \Delta z_{i} \right).
\tag{1}
$$


<!---

Something around here verbally presenting the logic of eqn 1, discussing how we are talking about an interaction between birth-death (individual fitness) and a individual's characteristic.

Also need to explain units of Omega, since there is confusion here.

--->

This foundation of eco-evolutionary change is a statistical interaction between the demographic processes of birth and death ($\beta_{i} - \delta_{i} + 1$) and some characteristic of an individual ($z_{i} + \Delta z_{i}$).
The value of $\Omega$ is a summation of individual characteristics and takes the same units as $z$.
From eqn 1, we can derive the most fundamental equations of population ecology and evolutionary biology through an appropriate interpretation of $z$.
Under more limited interpretations of $z$, we can also interpret $\Omega$ as a metric of ecosystem function.


<!---

19 MAY: Point out here that by itself, Omega has the same terms as z. 

- Verbally, our equation shows interaction between fitness and an individual's characteristic, summed
- Because it is summing across individuals, some characteristics can be interpreted as measure of ecosystem function
- Ecosystem function will make the assumption of additivity of z_i across all N
- We will see that mean fitness is population ecology
- Variance is evolutionary change
- Summation is ecosystem function

Eqn 1 captures an invariant relationship between individual fitness and an individual's characteristic


Also note that directly tying fitness to demography

--->


Population ecology
====================================================

To recover the general equation for population ecology (Box 2), we define $z_{i}$ as the identity of $i$ belonging to the population.
In other words, we set $z_{i} = 1$ to simply indicate that $i$ is one member of the population.
In this restricted case, $z$ is count, which takes the unit 1 [note that 'individual' is a label, not a unit, see @NewellEtAl2019].
Further, we assume that individuals do not change species by setting $\Delta z_{i} = 0$.
In this case,

$$\Omega = \sum_{i=1}^{N} \left(\beta_{i} - \delta_{i} + 1 \right).$$

We can now interpret $\Omega$ as the population size at $t+1$, $N_{t+1}$.
Summing up $\beta_{i}$, $\delta_{i}$, and current individuals tallies up the total number of individuals in the next time step,

$$N_{t+1} = N_{t} + Births - Deaths.
\tag{2}
$$

If we assume that individuals are identical, then we can drop the subscript $i$ such that $\beta_{i} = \beta$ and $\delta_{i} = \delta$ and note that $N\beta$, $N\delta$, and $N$ are the total births, total deaths, and size of the population at $t$, respectively,

Summing from 1 to $N$, we can rewrite the above,

$$\Omega = N\left(1 + \beta - \delta \right).$$

If we define $\lambda = 1 + \beta - \delta$ (Box 2), then we can rewrite,

$$N_{t+1} = N_{t}\lambda.
\tag{3}
$$

We therefore recover the general equation for population ecology (eqn 2) and the fundamental property of exponential growth in populations [eqn 3, @Turchin2001].


Evolutionary biology
====================================================

Recovering the Price equation requires a few more steps.
We start by defining individual fitness,

$$w_{i} = \beta_{i} - \delta_{i} + 1.
\tag{4}
$$

In this definition, the longevity of the individual matters.
By definition, an individual that survives from $t$ to $t + 1$ has a higher fitness than one that dies, even if both have the same reproductive output.
With this definition of fitness (eqn 4), we substitute,

$$\Omega = \sum_{i=1}^{N} \left(w_{i}z_{i} + w_{i}\Delta z_{i} \right).
\tag{5}
$$

We can break eqn 5 down further and multiply each side by $1/N$,

$$\frac{1}{N}\Omega = \frac{1}{N}\sum_{i=1}^{N} \left(w_{i}z_{i} \right) + \frac{1}{N}\sum_{i=1}^{N}\left( w_{i}\Delta z_{i} \right).
\tag{6}
$$

We can rewrite the terms on the right-hand side of eqn 6 as expected values and remove the subscripts,

$$\frac{1}{N}\Omega = \mathrm{E}\left(w z \right) + \mathrm{E}\left( w \Delta z  \right).
\tag{7}
$$

Now we must consider the total conservation of probability [@Frank2015; @Frank2016].
In eqn 7, $\Omega$ is the total sum trait values ($z_{i}$) across the entire population at $t + 1$ divided by the number of individuals ($N$) in the population at $t$.
But the size of the population can change from $t$ to $t + 1$.
To recover mean trait change for the Price equation (and therefore conserve total probability), we need to account for this change in population size.
The left-hand side of eqn 7 describes contributions to the sum trait value from the new population at $t + 1$.
But we cannot treat $\Omega/N$ as the mean of $z$ at $t+1$ ($\bar{z}'$) because we need to weight $N$ by the mean fitness of the population at $t$ to account for any change in population size from $t$ to $t+1$.

For example, if mean fitness at $t$ is 2 (i.e., $\bar{w} = 2$), then half as many individuals will have contributed to $\Omega$ in $t + 1$ than would have if $\bar{w} = 1$ (i.e., there are $N$ individuals at $t$ and $2N$ individuals at $t + 1$).
We therefore need to multiply the mean trait value $\bar{z}'$ (at $t + 1$) by the mean fitness $\bar{w}$ (at $t$) to recover the mean contribution of the $N$ individuals at $t$ to the total $\Omega$ [this has been applied in the context of population genetics by @Ewens2014].
Consequently, 

$$\Omega = N\bar{w}\bar{z}'
\tag{8}
$$

Equation 8 conserves the total probability and now clarifies $\Omega$ as a summed trait value, which has the same units as $z$ and equals expected population growth at $t$ times mean trait value at $t + 1$.
This is consistent with the population ecology derivation from the previous section where $z_{i} = 1$ by definition, and $\Omega = N_{t+1}$ (note $\lambda = \bar{w}$).
We can therefore rewrite eqn 7,

$$\bar{w}\bar{z}' = \mathrm{E}\left(w z \right) + \mathrm{E}\left( w \Delta z  \right).
\tag{9}
$$

We can rearrange eqn 9 to derive the Price equation by expressing covariance as $\mathrm{Cov}(X,Y) = \mathrm{E}(XY) - \mathrm{E}(X)\mathrm{E}(Y)$, and therefore $\mathrm{E}(XY) = \mathrm{Cov}(X,Y) + \mathrm{E}(X)\mathrm{E}(Y)$.
Substituting into eqn 9,

$$\bar{w}\bar{z}' = \mathrm{Cov}\left(w ,z \right) + \bar{w}\bar{z} + \mathrm{E}\left( w \Delta z  \right).$$

From here,

$$\bar{w}\left(\bar{z}' - \bar{z}\right) = \mathrm{Cov}\left(w ,z \right) + \mathrm{E}\left( w \Delta z  \right).$$

Since $\Delta \bar{z} = \left(\bar{z}' - \bar{z}\right)$,

$$\bar{w}\Delta \bar{z} = \mathrm{Cov}\left(w ,z \right) + \mathrm{E}\left( w \Delta z  \right).
\tag{10}
$$

Equation 10 is the Price equation.
From eqn 1, which describes fundamental birth and death processes in a population, we can therefore derive both the most fundamental model of population ecology (eqn 2; Box 2) and the fundamental equation of evolution (eqn 10; Box 1).


Ecosystem function
====================================================

In some cases, $\Omega$ could also be interpreted as the total contribution of a population to ecosystem function.
This is restricted to cases in which $z$ is a characteristic defining an absolute quantity measured at the whole organism level such as biomass, seed production, carbon capture, flower visits, or nutrient consumption.
In such cases, the sum across individuals gives a meaningful total quantity for the population (e.g., the total biomass or seeds produced in the population).
When $z$ is instead defined by relative organism-level measurements such wing loading, nutrient ratio, or diet composition, or when $z$ is measured at a level of biological organisation below the organism (e.g., average cell volume or leaf surface area), $\Omega$ does not have a clear population-level interpretation.
In such cases, eqn 1 still defines eco-evolutionary change; the interpretation of $\Omega$ by itself is just not as interesting, biologically.

Box 3 provides an instructive example of three plants with different fitnesses and carbon captures.
We use this example to demonstrate a concrete example of our proposed framework.

*******************

> **Box 3:** As an instructive example of our framework, consider a population of $N_{t} = 3$ annual plants in which individual total fruit mass (kg) is measured, and change is observed over a year. For all plants, $\delta_{i} = 1$ (because annual plants die between $t$ and $t+1$), and let plant fecundities be $\beta_{1} = 1$, $\beta_{2} = 1$, and $\beta_{3} = 2$. Applying eqn 1 to population change such that $\Omega = N_{t+1}$, $z_{i} = 1$ and $\Delta z_{i} = 0$, $N_{t+1} = (1 - 1 + 1)(1 + 0) + (1 - 1 + 1)(1 + 0) + (2 - 1 + 1)(1 + 0) = 4$ (note $\bar{w} = 4/3$, so $N_{t}\bar{w} = 3(4/3) = 4$). Focusing next on the characteristic of total fruit mass, let $z_{1} = 0.8$ kg, $z_{2} = 1.0$ kg, and $z_{3} = 1.5$ kg. Also let $\Delta z_{i} = 0.1$ for all plants to reflect a change in soil environment from $t$ to $t + 1$. In this case, population fruit yield at $t+1$ is $\Omega = (1 - 1 + 1)(0.8 + 0.1) + (1 - 1 + 1)(1.0 + 0.1) + (2 - 1 + 1)(1.5 + 0.1) = 5.2$ kg. At $t$, mean fruit yield per plant was $(0.8 + 1.0 + 1.5)/3 = 1.1$ kg, but at $t+1$, mean fruit yield per plant is $[(0.8 + 0.1) + (1.0 + 0.1) + 2(1.5 + 0.1)]/4 = 1.3$ kg. Note that $\mathrm{Cov}(w, z) = (1/N)\sum_{i}^{N}(z_{i} - \bar{z})(w_{i} - \bar{w}) = (1/3)\left[(0.8 - 1.1)(1-4/3) + (1 - 1.1)(1-4/3) + (1.5 - 1.1)(2-4/3) \right]  = 2/15$ and $\mathrm{E}(w \Delta z) = 4/3 \times 0.1 = 2/15$, so applying the Price equation, $\bar{w}\Delta \bar{z} = 2/15 + 2/15 = 4/15$. Since $\bar{w} = 4/3$, multiplying both sides of the equation by $3/4$ returns $\Delta z = 0.2$, which is the mean difference in fruit yield between $t+1$ and $t$. The framework expressed in eqn 1 thereby links population change, evolutionary change, and ecosystem function.

*******************

Discussion
====================================================

An important aspect of scientific progress is the ability to connect disparate theories and models to show how specific empirical and theoretical models are logical (mathematical) consequences of more fundamental ones [@Nagel1961; @Morrison2000].
Rather than making simplifying assumptions, as is the approach for specific ecological and evolutionary models, we focus on fundamental axioms that are universal to closed biological systems: discrete individuals, birth, death, and change over time.
We define an abstract sum ($\Omega$), to which all individuals within the population contribute.
From the basic axiom that each individual is one member of a specific population ($z_{i} = 1$ and $\Delta z_{i} = 0$), we recover the most general equation of population ecology (Box 2) and the principle of exponential growth ($N_{t+1} = N_{t}\lambda$).
By defining individual fitness ($w_{i}$) and applying the total conservation of probability to individual frequencies [@Frank2015; @Frank2016], we recover the most fundamental equation of evolution, the Price equation (Box 1).
Our eqn 1 thereby provides a foundation for defining eco-evolutionary change in any population.


The Price equation provides a complete and exact description of evolution in any closed evolving system [@Price1970; @Frank2012].
It is derived by rearranging the mathematical notation defining changes in the frequencies and characteristics of any type of entity [e.g., individuals, alleles, @Price1970; @Gardner2008; @Luque2016].
This derivation partitions total characteristic change into different components, making it possible to isolate evolutionary mechanisms (e.g., selection) and levels of biological organisation (e.g., group, individual) [@Frank1995; @Kerr2009; @Frank2012; @Luque2016; @Okasha2020].
Because of its abstract nature and lack of any system-specific assumptions, the Price equation is not dynamically sufficient and makes no predictions about what will happen in any particular system [@Gardner2020].
Its role is not to predict, but to formally and completely define and separate components of evolutionary change [@Baravalle2024]. 
The same is true of the general equation for population change (eqn 2), at least as we have used it here where it serves to define what population growth means in ecology.
This equation formally and completely describes population change in terms of births and deaths.
In eqn 1, we therefore have a fundamental equation from which we can derive complete ecological and evolutionary change in any closed biological population.
Like all fundamental equations, our equation is necessarily abstract and not dynamically sufficient.
We believe that it will be useful for eco-evolutionary theory in a similar way that the Price equation is useful for evolutionary theory: potentially facilitating specific model development and identifying new conceptual insights, unresolved errors, and sources of model disagreements (see below and Supporting Information S1).


Our unification recovers the equivalence between the finite rate of increase $\lambda$ (Box 2) and population mean evolutionary fitness $\bar{w}$ (Box 1).
The population growth equation $N_{t+1} = N_{t}\lambda$ can always be rewritten as $N_{t+1} = N_{t}\bar{w}$.
This specific equivalence has been proposed before [e.g., @Lande1976], as has the broader relationship between population growth rate and evolutionary fitness [@Fisher1930; @Charlesworth1980; @Lande1982; @Roff2008; @Lion2018].
We show this from first principles and clarify the relationship between fitness and population growth.
Over an arbitrary length of time, fitness is properly defined as $w_{i} = \beta_{i} - \delta_{i} + 1$.
Over an individual's lifetime (which, by definition, includes death), fitness is therefore $\beta_{i}$. 
Rates of change in ecology and evolution are reflected in the first and second statistical moments of fitness, respectively.
Population growth rate reflects mean fitness $\bar{w}$, while the rate of evolutionary change reflects the variance in fitness $\mathrm{Var}(w)/\bar{w}$ [i.e., Fisher's fundamental theorem, @Frank1997; @Rice2004; @Queller2017].


Our unification may also help explain, at least partially, some of the success of classical population genetic models. 
For decades, population genetics (and to some extent quantitative genetics) has been accused of being a reductionist view of evolution, reducing everything to changes in allele frequencies and abstracting away from individuals and their environments [the ecological interactions, @MacColl2011]. 
This has been a line of argumentation by some defenders of the so-called Extended Synthesis [@Pigliucci2009], especially in relation to niche construction [@Odling-smee2003].
Famously, @Mayr1960 characterised population genetics as a simple input and output of genes, analogous to "the adding of certain beans to a beanbag and the withdrawing of others" (also called "beanbag genetics"). 
Historical critics of population genetics could not articulate a clear explanation for why it works so well despite all of its idealisations and simplifications.
From the Price equation, we are able to recover classical population and quantitative genetic models [@Queller2017] and develop new ones [@Rice2004; @Rice2020; @Luque2016; @Lion2018].
Our eqn 1 contains ecology at its core, and we show how the Price equation logically follows from it after accounting for absolute population growth (eqn 8).
We therefore conclude that population and quantitative genetic equations contain ecology (no matter how hidden), and the ecological nature of evolution is implicit in population and quantitative genetic models.


We have focused on the dynamics of a closed population, and in doing so leave ecological and evolutionary change attributable to migration for future work.
In population ecology, immigration and emigration can be incorporated by adding a term for each to the right-hand side of the equation in Box 2 [@Gotelli2001].
In evolution, because the Price equation relies on mapping ancestor-descendant relationships, accounting for migration is more challenging.
@Kerr2009 demonstrate how the Price equation can be extended to allow for arbitrary links between ancestors and descendants, thereby extending the Price equation to allow for immigration and emigration. 
@Frank2012 presents a simplified version of @Kerr2009 that allows some fraction of descendants to be unconnected to ancestors.
In both ecology and evolution, accounting for migration is done through the use of additional terms on the right-hand side of the equations.

We believe our fundamental equation to be complete and exact for any closed population.
It therefore implicitly includes any effects of density dependence on population growth (see Box 2), or any social effects on evolutionary change (see Box 1).
Both of these effects can be made explicit by specifying how other individuals in a population affect birth and death of a focal individual.
We demonstrate this by deriving more specific models of density dependent population growth and multi-level selection in Supporting Information S1.
In Supporting Information S1, we also suggest how new theoretical insights might be gained by integrating density-dependent growth and social interactions into our framework.

We have shown that we can derive the fundamental equations of population ecology and biological evolution from a single unifying equation.
Lastly, we propose our eqn 1 as a potential starting point for defining ecosystem function and further conceptual unification between ecology, evolution, and ecosystem function.
The Price equation has previously been used to investigate ecosystem function [@Loreau2001; @Fox2006], but not with any attempt towards conceptual unification with evolutionary biology.
For example, @Fox2006 applied the abstract properties of the Price equation to partition total change in ecosystem function into separate components attributable to species richness, species composition, and context dependent effects.
This approach provides a framework for comparing the effects of biodiversity on ecosystem function in empirical systems [@Fox2006; @Winfree2015; @Mateo-Tomas2017].
Instead, our eqn 1 defines $\Omega$ as total ecosystem function contributed by a focal population.
It is therefore possible to investigate ecological, evolutionary, and ecosystem function change from the same shared framework.


Acknowledgements
====================================================

This manuscript was supported by joint funding between the French Foundation for Research on Biodiversity (FRB) Centre for the Synthesis and Analysis of Biodiversity (CESAB) and the German Centre for Integrative Biodiversity Research (sDiv).
It was written as part of the Unification of Modern Coexistence Theory and Price Equation (UNICOP) project.
Victor J. Luque was also supported by the Spanish Ministry of Science and Innovation (Project: PID2021-128835NB-I00), and the Conselleria  d’Innovaci$\'{o}$, Universitats, Ci$\`{e}$ncia i Societat Digital – Generalitat  Valenciana (Project: CIGE/2023/16).
We are grateful for many conversations with S$\'{e}$bastien Lion, Kelsey Lyberger, Swati Patel, and especially Lynn Govaert, whose questions helped us clarify the relationship between population growth and fitness.
Brad Duthie would also like to thank Matt Tinsley, Brent Danielson, and Stan Harpole.
Victor J. Luque would also like to thank Lorenzo Baravalle, Pau Carazo, Santiago Ginnobili, Manuel Serra, and Ariel Roff$\'{e}$.



Author Contributions
====================================================

Both authors came up with the question idea. 
Following many discussions between the authors, ABD proposed the initial equation with subsequent exploration and development from both authors. 
Both authors contributed to the writing.


Competing Interests
====================================================

The authors declare no competing interests.

Data Availability
====================================================

This work does not include any data.


References
====================================================

<div id="refs"></div>

\clearpage


Supporting Information S1
================================================

This supporting information demonstrates how to derive well-established models in population ecology and evolutionary biology from equation 1 in the main text,

$$\Omega = \sum_{i=1}^{N} \left(\beta_{i} - \delta_{i} + 1 \right)\left(z_{i} + \Delta z_{i} \right).
\tag{1}
$$


In the main text, we derived both the Price equation and the birth-death model from the above.
Here we integrate interactions between individuals to recover density-dependent population growth, and we integrate groups within the population to recover multi-level selection.
Finally, we integrate both to model a system in which multi-level selection and density dependent population change occur simultaneously.
We can do this in a way that clarifies model assumptions by allowing an individual $j$ to modulate the birth or death of the focal individual $i$.


Density-dependent population growth
===========================================

There are two potential ways to model the incorporation of density dependence into population growth.
We start with what is likely the most familiar model focusing on individual growth rate $r_{i}$, then use a slightly different model focusing on fitness $w_{i}$. 
First note that here we set $\Omega = N_{t+1}$, and $z_{i} = 1$ and $\Delta z_{i} = 0$ for all individuals as in the main text.
We can define $r_{i} = \beta_{i} - \delta_{i}$ as an individual growth rate for $i$ [@Lion2018; @Lion2023].
In this case,

$$N_{t+1} = \sum_{i=1}^{N_{t}}\left(r_{i} + 1\right)
\tag{S1}
$$

Mathematically, the most general approach here would be to define individual growth as a function of the entire system $\mathbf{E}$, $r_{i}(\mathbf{E})$, where $\mathbf{E}$ is a vector with elements including any parameters potentially relevant to $r_{i}$.
Taking this approach would recover a version of eqn 2 in @Lion2018 and permit any relationship between the system and a focal individual's growth.
Limiting our focus to the effects of other individuals ($j$) and assuming that the effects of these individuals are additive, let $a_{ij|\cdot}$ be the effect of individual $j$ on the growth rate attributable to $i$ conditioned on all other individuals within the population such that $r_{i}\left(1 + \sum_{i = j}^{N}a_{ij|\cdot} \right)$ defines the realised growth rate of $i$,

$$N_{t+1} = \sum_{i=1}^{N_{t}}\left(r_{i}\left(1 - \sum_{i = j}^{N_{t}}a_{ij|\cdot} \right) + 1\right).
\tag{S2}
$$

Assuming that individual effects of $j$ on $i$ are also independent, we can remove the condition,

$$N_{t+1} = \sum_{i=1}^{N_{t}}\left(r_{i}\left(1 - \sum_{i = j}^{N_{t}}a_{ij} \right) + 1\right).$$

Further assuming that all individuals have the same per capita effect such that $a = a_{ij}$ for any $i$ and $j$ pair (as might be reasonable given resource competition in a well-mixed population),

$$N_{t+1} = \sum_{i=1}^{N_{t}}\left(r_{i}\left(1 - a N_{t} \right) + 1\right).$$

If $r_{i}$ values are identical, 

$$N_{t+1} = N_{t} + r N_{t}\left(1 - a N_{t} \right).
\tag{S3}
$$

Equation S3 therefore recovers a classic version of a discrete time logistic growth by making assumptions from an exact model of eco-evolutionary change.


An alternative approach would be to define model the effects of an individual $j$ on the fitness of $i$ ($w_{i}$), thereby replacing eqn S1 with $N_{t+1} = \sum_{i=1}^{N_{t}}w_{i}$ and replacing eqn S2 with, 

$$N_{t+1} = \sum_{i=1}^{N_{t}}w_{i}\left(1 - \sum_{i = j}^{N_{t}}\alpha_{ij|\cdot} \right).
$$

Note that we have used $\alpha_{ij}$ to represent the effect of $j$ on the fitness of $i$ for clarity in the sections below.
By making the same assumptions of additivity, independence, and identical effects such that $\alpha = \alpha_{ij}$ for all $j$ on $i$, and assuming fitness is equal ($w_{i} = \bar{w}$), we can derive,

$$N_{t+1} = \bar{w}N_{t}(1 - \alpha N_{t}).
\tag{S4}
$$

This is an alternative way to express logistic growth.



Multi-level selection
=============================

We can recover multi-level selection from our eqn 1. 
Here we derive the original form of the multi-level @Price1972 equation as it appears in eqn 3.1 of @Lehtonen2020a.
Individuals belong to one of $K$ total groups where $j$ indexes $K$ groups and $i$ indexes individuals. 
Individuals do not overlap in group membership. 
The size of group $j$ is denoted as $N_{j}$.
Equation S5 below uses summations to partition how individuals within each group contribute to $\Omega$,

$$\Omega = \sum_{j=1}^{K}\sum_{i=1}^{N_{j}}\left(\beta_{j,i} - \delta_{j,i} + 1 \right)\left(z_{j, i} + \Delta z_{j, i}\right).
\tag{S5}
$$

In S5, indices $\beta_{j, i}$, $\delta_{j, i}$, and $z_{j, i}$ identify individual $i$ in group $j$.
We set $w_{j, i} = \beta_{j, i} - \delta_{j, i} + 1$, and for simplicity let $\Delta z_{j, i} = 0$ (i.e., no transmission bias),

$$\Omega = \sum_{j=1}^{K}\sum_{i=1}^{N_{j}}w_{j,i}z_{j, i}.$$

For ease of presentation, with no loss of generality, we assume all group sizes are equal with a group size of $N_{j} = n$ for all $j$.
If group sizes differ, then weighted expectations and covariances are instead needed [@Lehtonen2020a].
Given equal group sizes, the total number of individuals ($N$) equals $K \times n$, and,

$$\frac{\Omega}{K n} = \left(\frac{1}{K}\right)\left(\frac{1}{n}\right)\sum_{j=1}^{K}\sum_{i=1}^{n}w_{j,i}z_{j, i}.$$

Rearranging,

$$\frac{\Omega}{K n} = \frac{1}{K}\sum_{j=1}^{K}\frac{1}{n}\sum_{i=1}^{n}w_{j,i}z_{j, i}.$$

The inner summation can be rewritten as an expectation for group $j$,

$$\frac{\Omega}{K n} = \frac{1}{K}\sum_{j=1}^{K}\mathrm{E}_{j}\left(w_{j,i} z_{j,i}\right).$$

As in the main text, we note $\mathrm{E}(XY) = \mathrm{Cov}(X,Y) + \mathrm{E}(X)\mathrm{E}(Y)$.
Defining $Cov_{j}(w_{j}, z_{j})$ as the covariance between $w_{j,i}$ and $z_{j, i}$ for group $j$,

$$\frac{\Omega}{K n} = \frac{1}{K}\sum_{j=1}^{K}\mathrm{Cov}_{j}\left(w_{j,i}, z_{j,i}\right) + \mathrm{E}_{j}\left(w_{j,i}\right)\mathrm{E}_{j}\left(z_{j,i}\right).$$

We can separate the summation for each term,

$$\frac{\Omega}{K n} = \frac{1}{K}\sum_{j=1}^{K}\mathrm{Cov}_{j}\left(w_{j,i}, z_{j,i}\right) + \frac{1}{K}\sum_{j=1}^{K}\mathrm{E}_{j}\left(w_{j,i}\right)\mathrm{E}_{j}\left(z_{j,i}\right).$$

Using the notation $\bar{w}_{j} = E_{j}(w_{j,i})$ and $\bar{z}_{j} = E_{j}(z_{j,i})$ to indicate the expectation in group $j$,

$$\frac{\Omega}{K n} = \frac{1}{K}\sum_{j=1}^{K}\mathrm{Cov}_{j}\left(w_{j,i}, z_{j,i}\right) + \mathrm{E}\left(\bar{w}_{j} \bar{z}_{j} \right).$$

We can also rewrite the first term on the right-hand side as an expectation,

$$\frac{\Omega}{K n} = \mathrm{E}\left(\mathrm{Cov}_{j}\left(w_{j}, z_{j}\right)\right) + \mathrm{E}\left(\bar{w}_{j} \bar{z}_{j} \right).$$

We can rearrange the second term on the right-hand side ($\bar{\bar{w}}$ indicates grand mean over all groups),

$$\frac{\Omega}{K n} = \mathrm{E}\left(\mathrm{Cov}_{j}\left(w_{j}, z_{j}\right)\right) +  \mathrm{Cov}\left(\bar{w}_{j}, \bar{z}_{j} \right) + \bar{\bar{w}}\bar{\bar{z}}.$$

As in the main text, note that $Kn\bar{\bar{w}}$ accounts for differences in total population size from $t$ to $t+1$, with $\bar{\bar{w}}$ being mean fitness across all groups.
We can therefore set $\Omega = Kn\bar{\bar{w}}\bar{\bar{z'}}$, so,

$$\frac{Kn\bar{\bar{w}}\bar{\bar{z'}}}{K n} - \bar{\bar{w}}\bar{\bar{z}} = \mathrm{E}\left(\mathrm{Cov}_{j}\left(w_{j}, z_{j}\right)\right) +  \mathrm{Cov}\left(\bar{w}_{j}, \bar{z}_{j} \right).$$

Because $\Delta \bar{\bar{z}} = \bar{\bar{z'}} - \bar{\bar{z}}$,

$$\bar{\bar{w}}\Delta \bar{\bar{z}} = \mathrm{Cov}\left(\bar{w}_{j}, \bar{z}_{j} \right) + \mathrm{E}\left(\mathrm{Cov}_{j}\left(w_{j}, z_{j}\right)\right).
\tag{S6}
$$

This recovers the multi-level @Price1972 equation [@Lehtonen2020a] from a starting point of eco-evolutionary change in different groups.
Equation S6 can be found in @Lehtonen2016 B2.I, who then derives a multi-level selection version of Hamilton's rule predicting the evolution of altruism.



Integration of ecology and evolution
========================================

For simplicity, we now focus on showing an integration between ecology and evolution using a population with no multi-level selection and let $\Delta z_{j, i} = 0$ (i.e., no transmission bias).
As above in the section on density-dependent population growth, we define $w_{i} = \beta_{i} - \delta_{i} + 1$ and use $\alpha_{i,j}$ to represent the effect of $j$ on the fitness of $i$.
Our starting equation is therefore,

$$\Omega = \sum_{i=1}^{N}w_{i}\left(1 - \sum_{j=1}^{N}\alpha_{i, j}\right)z_{i}.
\tag{S7}
$$

We have already demonstrated that if we assume all individuals have the same effect on a focal individual such that $\alpha = \alpha_{i,j}$ for all $i$ and $j$ pairs, we can recover equation S4 when $z_{i} = 1$ and $\Omega$ is therefore interpreted as the count of entities,

$$N_{t+1} = \bar{w} N_{t} \left(1 - \alpha N_{t}\right).$$


We now start from S7 to derive $\Delta \bar{z}$.
The objective is to use our definition of eco-evolutionary change to simultaneously recover how interactions between individuals affect population change and evolutionary change.

We start by dividing both sides of S7 by $N$,

$$\frac{\Omega}{N} = \frac{1}{N}\sum_{i=1}^{N}w_{i}\left(1 - \sum_{j=1}^{N}\alpha_{i, j}\right)z_{i}.
\tag{S8}
$$


We can express the right-hand side of eqn S8 as an expectation,

$$\frac{\Omega}{N} = \mathrm{E}\left(w_{i}\left(1 - \sum_{j=1}^{N}\alpha_{i, j}\right)z_{i}\right).
\tag{S9}
$$


We can rewrite the right-hand side in terms of covariances,


$$\frac{\Omega}{N} = \mathrm{Cov}\left(w_{i}\left(1 - \sum_{j=1}^{N}\alpha_{i, j}\right), z_{i}  \right) + \mathrm{E}\left(w_{i}\left(1 - \sum_{j=1}^{N}\alpha_{i, j}\right)\right)\mathrm{E}\left(z_{i}\right). 
\tag{S9}
$$


The expectations in the second term on the right-hand side can be replaced with overbars to represent the mean,

$$\frac{\Omega}{N} = \mathrm{Cov}\left(w_{i}\left(1 - \sum_{j=1}^{N}\alpha_{i, j}\right), z_{i}  \right) + \overline{w_{i}\left(1 - \sum_{j=1}^{N}\alpha_{i, j}\right)}    \bar{z}_{i}. 
\tag{S9}
$$

In the main text, we noted that $\Omega = N\bar{w}\bar{z}'$.
Here mean fitness incorporates individual interactions, therefore,

$$\Omega = N\overline{w_{i}\left(1 - \sum_{j=1}^{N}\alpha_{i, j}\right)}\bar{z}'.
\tag{S10}
$$


We can therefore rewrite S9,

$$\overline{w_{i}\left(1 - \sum_{j=1}^{N}\alpha_{i, j}\right)}\bar{z}' -  \overline{w_{i}\left(1 - \sum_{j=1}^{N}\alpha_{i, j}\right)}    \bar{z}_{i} = \mathrm{Cov}\left(w_{i}\left(1 - \sum_{j=1}^{N}\alpha_{i, j}\right), z_{i}  \right). 
\tag{S11}
$$


Noting again $\Delta \bar{z} = \bar{z}' - \bar{z}$,

$$\overline{w_{i}\left(1 - \sum_{j=1}^{N}\alpha_{i, j}\right)}\Delta\bar{z} = \mathrm{Cov}\left(w_{i}\left(1 - \sum_{j=1}^{N}\alpha_{i, j}\right), z_{i}  \right). 
\tag{S12}
$$


We can rewrite the left-hand side of S12,

$$\overline{w_{i}\left(1 - \sum_{j=1}^{N}\alpha_{i, j}\right)}\Delta\bar{z} = \mathrm{Cov}\left(w_{i} - w_{i}\sum_{j=1}^{N}\alpha_{i, j}, z_{i}  \right). 
\tag{S13}
$$


The covariance term can be split without any additional assumptions,

$$\overline{w_{i}\left(1 - \sum_{j=1}^{N}\alpha_{i, j}\right)}\Delta\bar{z} = \mathrm{Cov}\left(w_{i}, z_{i}  \right) - \mathrm{Cov}\left(w_{i}\sum_{j=1}^{N}\alpha_{i, j}, z_{i}  \right). 
\tag{S14}
$$


If we are able to further assume that $w_{i}$ and the summation over $\alpha_{i,j}$ are independent, then we could rewrite,

$$\overline{w_{i}\left(1 - \sum_{j=1}^{N}\alpha_{i, j}\right)}\Delta\bar{z} = \mathrm{Cov}\left(w_{i}, z_{i}  \right) - \mathrm{Cov}\left(\sum_{j=1}^{N}\alpha_{i, j}, z_{i}  \right)\bar{w_{i}}. 
\tag{S15}
$$

Partitioning fitness into different components with the Price equation is commonplace.
But this derivation highlights, e.g., the ecological and evolutionary relationship between nonsocial and social components of fitness, and population size.
For example, the second term on the right-hand side of S13 shows the covariance between the sum of social interactions and a trait.
When traits covary with the interaction between sociality and fitness, they will have a stronger effect on trait change.
The magnitude of this second term will also increase with $N$, which reflects the stronger effect of the interaction between sociality and fitness when there are more individuals interacting with a focal individual.



<!---


We can start again with $K$ groups and let $\Delta z_{j, i} = 0$ (i.e., no transmission bias).
But for simplicity, now consider the case in which $\delta_{j,i} = 1$ (complete mortality), and consider $w_{j, i} = \beta_{j, i}(1 - \sum_{p=1}^{K}\sum_{q=1}^{n} \alpha^{j, i}_{p,q})$, where $\alpha^{j, i}_{p,q}$ is the effect that individual $q$ from group $p$ has on a focal individual $i$ from group $j$.
To keep the model tractable, we assume that all individuals within a group $p$ have identical effects on any focal individual in the group $j$, such that $w_{j, i} = \beta_{j, i}(1 - \sum_{p=1}^{K} \alpha^{j}_{p} n)$

$$\Omega = \sum_{j=1}^{K}\sum_{i=1}^{n}\beta_{j, i}\left(1 - \sum_{p=1}^{K} \alpha^{j}_{p} n\right)z_{j, i}.
\tag{S7}
$$

Our objective here is to start from the above equation and recover population growth and multi-level selection given this parameterisation focused on individual birth as affected by other individuals in the population.
If we set $z_{j, i} = 1$ as we have done for population ecology, we can recover logistic growth,

$$N_{t+1} = \sum_{j=1}^{K}\sum_{i=1}^{n}\beta_{j, i}\left(1 - \sum_{p=1}^{K} \alpha^{j}_{p} n\right).$$

If we ignore groups and note $N_{t} = nK$, and we assume that the per capita effect of every individual from every group on a focal individual is equal (i.e., $\alpha = \alpha^{j}_{p}$ for all groups), 

$$N_{t+1} = N_{t}\beta_{j, i}\left(1 - \alpha N_{t}\right).$$

We therefore derive the model for population change.

We now use the same starting point to carry the effects of individuals on fitness through a model of multi-level selection.
Rearranging S7,


$$\Omega = \sum_{j=1}^{K}\sum_{i=1}^{n}\left(\beta_{j, i} - \beta_{j, i}\sum_{p=1}^{K} \alpha^{j}_{p} n\right)z_{j, i}.$$

As we have done previously, we can multiply both sides of the equation by $(1/K)(1/n)$,

$$\frac{\Omega}{K n} = \frac{1}{K}\sum_{j=1}^{K}\frac{1}{n}\sum_{i=1}^{n}\left(\beta_{j, i} - \beta_{j, i}\sum_{p=1}^{K} \alpha^{j}_{p} n\right)z_{j, i}.$$

We can rewrite the inner summation as an expectation for group $j$,

$$\frac{\Omega}{K n} = \frac{1}{K}\sum_{j=1}^{K}E\left(\left(\beta_{j, i} - \beta_{j, i}\sum_{p=1}^{K} \alpha^{j}_{p} n\right)z_{j, i}\right).$$

We can rewrite the product within the expectation as a covariance plus a product of the expectations and split the covariance (note that $Cov(X-Y, Z) = Cov(X, Z) - Cov(Y, Z)$),

$$\frac{\Omega}{K n} = \frac{1}{K}\sum_{j=1}^{K}Cov\left(\beta_{j, i}, z_{j,i}\right) - Cov\left(\beta_{j, i}\sum_{p=1}^{K} \alpha^{j}_{p} n, z_{j,i}\right) + E\left(\beta_{j, i} - \beta_{j, i}\sum_{p=1}^{K} \alpha^{j}_{p} n\right) E\left(z_{j, i}\right).$$

All terms are within the summation, which can therefore be separated,


$$\frac{\Omega}{K n} = \frac{1}{K}\sum_{j=1}^{K}Cov\left(\beta_{j, i}, z_{j,i}\right) - \frac{1}{K}\sum_{j=1}^{K}Cov\left(\beta_{j, i}\sum_{p=1}^{K} \alpha^{j}_{p} n, z_{j,i}\right) + \frac{1}{K}\sum_{j=1}^{K}E\left(\beta_{j, i} - \beta_{j, i}\sum_{p=1}^{K} \alpha^{j}_{p} n\right) E\left(z_{j, i}\right).$$


Note that because $E(X - Y) \times E(Z) = E(X)E(Z) - E(Y)E(Z)$, the third term on the right-hand side can be split,

\begin{align*}
\frac{\Omega}{K n} &= \frac{1}{K}\sum_{j=1}^{K}Cov\left(\beta_{j, i}, z_{j,i}\right) - \frac{1}{K}\sum_{j=1}^{K}Cov\left(\beta_{j, i}\sum_{p=1}^{K} \alpha^{j}_{p} n, z_{j,i}\right) \\
                   &+ \frac{1}{K}\sum_{j=1}^{K}E\left(\beta_{j, i}\right)E\left(z_{j, i}\right) - E\left(\beta_{j, i}\sum_{p=1}^{K} \alpha^{j}_{p} n\right)E\left(z_{j, i}\right).
\end{align*}


We can rewrite this third term as an expectation,

\begin{align*}
\frac{\Omega}{K n} &= \frac{1}{K}\sum_{j=1}^{K}Cov\left(\beta_{j, i}, z_{j,i}\right) - \frac{1}{K}\sum_{j=1}^{K}Cov\left(\beta_{j, i}\sum_{p=1}^{K} \alpha^{j}_{p} n, z_{j,i}\right) \\
                   &+ E\left(E\left(\beta_{j, i}\right)E\left(z_{j, i}\right) - E\left(\beta_{j, i}\sum_{p=1}^{K} \alpha^{j}_{p} n\right)E\left(z_{j, i}\right)\right).
\end{align*}

Because of the linearity of expectation, we can again separate the third term on the right-hand side of the equation,

\begin{align*}
\frac{\Omega}{K n} &= \frac{1}{K}\sum_{j=1}^{K}Cov\left(\beta_{j, i}, z_{j,i}\right) - \frac{1}{K}\sum_{j=1}^{K}Cov\left(\beta_{j, i}\sum_{p=1}^{K} \alpha^{j}_{p} n, z_{j,i}\right) \\
                   &+ E\left(E\left(\beta_{j, i}\right)E\left(z_{j, i}\right)\right) - E\left(E\left(\beta_{j, i}\sum_{p=1}^{K} \alpha^{j}_{p} n\right)E\left(z_{j, i}\right)\right).
\end{align*}

For convenience, we substitute $E(\beta_{j,i}) = \bar{\beta}_{j,i}$ and $E(z_{j,i}) = \bar{z}_{j,i}$,

\begin{align*}
\frac{\Omega}{K n} &= \frac{1}{K}\sum_{j=1}^{K}Cov\left(\beta_{j, i}, z_{j,i}\right) - \frac{1}{K}\sum_{j=1}^{K}Cov\left(\beta_{j, i}\sum_{p=1}^{K} \alpha^{j}_{p} n, z_{j,i}\right) \\
                   &+ E\left(\bar{\beta}_{j, i} \bar{z}_{j, i}\right) - E\left(E\left(\beta_{j, i}\sum_{p=1}^{K} \alpha^{j}_{p} n\right)E\left(z_{j, i}\right)\right).
\end{align*}

We can split the third term above into a covariance and product of means,

\begin{align*}
\frac{\Omega}{K n} &= \frac{1}{K}\sum_{j=1}^{K}Cov\left(\beta_{j, i}, z_{j,i}\right) - \frac{1}{K}\sum_{j=1}^{K}Cov\left(\beta_{j, i}\sum_{p=1}^{K} \alpha^{j}_{p} n, z_{j,i}\right)\\ 
                   &+ Cov\left(\bar{\beta}_{j, i}, \bar{z}_{j, i}\right) + \bar{\bar{\beta}}_{j,i}\bar{\bar{z}}_{j,i} - E\left(E\left(\beta_{j, i}\sum_{p=1}^{K} \alpha^{j}_{p} n\right)E\left(z_{j, i}\right)\right).
\end{align*}

We can then do the same for the last term on the right-hand side,

\begin{align*}
\frac{\Omega}{K n} &= \frac{1}{K}\sum_{j=1}^{K}Cov\left(\beta_{j, i}, z_{j,i}\right) - \frac{1}{K}\sum_{j=1}^{K}Cov\left(\beta_{j, i}\sum_{p=1}^{K} \alpha^{j}_{p} n, z_{j,i}\right) \\
                   &+ Cov\left(\bar{\beta}_{j, i}, \bar{z}_{j, i}\right) + \bar{\bar{\beta}}_{j,i}\bar{\bar{z}}_{j,i} - Cov(\overline{\beta_{j, i}\sum_{p=1}^{K} \alpha^{j}_{p} n}, \bar{z}_{j,i}) - \overline{\overline{\beta_{j, i}\sum_{p=1}^{K} \alpha^{j}_{p} n}}\times\bar{\bar{z}}_{j,i}.
\end{align*}






As in the previous section of this supporting information, we note that $\Omega = Kn\bar{\bar{w}}\bar{\bar{z'}}$.
In this case, fitness $w_{j, i} = \beta_{j, i}(1 - \sum_{p=1}^{K} \alpha^{j}_{p} n)$

\begin{align*}
\bar{\bar{w}}\Delta\bar{\bar{z}} &= \frac{1}{K}\sum_{j=1}^{K}Cov\left(\beta_{j, i}, z_{j,i}\right) - \frac{1}{K}\sum_{j=1}^{K}Cov\left(\beta_{j, i}\sum_{p=1}^{K} \alpha^{j}_{p} n, z_{j,i}\right) \\ 
                                 &+ Cov\left(\bar{\beta}_{j, i}, \bar{z}_{j, i}\right) - Cov(\overline{\beta_{j, i}\sum_{p=1}^{K} \alpha^{j}_{p} n}, \bar{z}_{j,i}).
\end{align*}




And finally,

$$\bar{\bar{w}}\Delta\bar{\bar{z}} = E\left(Cov\left(\beta_{j}, z_{j}\right)\right) - E\left(Cov\left(\beta_{j}\sum_{p=1}^{K} \alpha^{j}_{p} n, z_{j,i}\right)\right) + Cov\left(\bar{\beta}_{j, i}, \bar{z}_{j, i}\right) - Cov(\overline{\beta_{j, i}\sum_{p=1}^{K} \alpha^{j}_{p} n}, \bar{z}_{j,i}).$$

This seems intuitive in that it just adds two terms to the derivation of multi-level selection.
And given how we have defined $\alpha$, this should relate the evolutoinary change in some trait $z$ to interactions, specifically density dependent decreases in fitness in this case.
Note that if $\alpha = 0$, the second and fourth terms drop out, as they should because the covariance with the trait is zero.



--->







Supporting Information References 
==========================

\addcontentsline{toc}{section}{References}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-Lehtonen2016}
Lehtonen, Jussi. 2016. {``{Multilevel selection in kin selection
language}.''} \emph{Trends in Ecology and Evolution} xx: 1--11.
\url{https://doi.org/10.1016/j.tree.2016.07.006}.

\bibitem[\citeproctext]{ref-Lehtonen2020a}
---------. 2020. {``The Price Equation and the Unity of Social Evolution
Theory.''} \emph{Philosophical Transactions of the Royal Society B:
Biological Sciences} 375: 20190362.
\url{https://doi.org/10.1098/rstb.2019.0362}.

\bibitem[\citeproctext]{ref-Lion2018}
Lion, Sébastien. 2018. {``{Theoretical approaches in evolutionary
ecology: environmental feedback as a unifying perspective}.''}
\emph{American Naturalist} 191 (1).
\url{https://doi.org/10.1086/694865}.

\bibitem[\citeproctext]{ref-Lion2023}
Lion, Sébastien, Akira Sasaki, and Mike Boots. 2023. {``Extending
Eco-Evolutionary Theory with Oligomorphic Dynamics.''} \emph{Ecology
Letters} 26 (September): S22--46.
\url{https://doi.org/10.1111/ele.14183}.

\bibitem[\citeproctext]{ref-Price1972}
Price, George R. 1972. {``{Extension of covariance selection
mathematics}.''} \emph{Annals of Human Genetics} 35 (4): 485--90.
\url{https://doi.org/10.1111/j.1469-1809.1957.tb01874.x}.

\end{CSLReferences}































