---
title: "Foundations of community ecology"
author: |
  | A. Bradley Duthie$^{1,a,*}$ and Victor J. Luque$^{2,a}$
date: '[1] Department of Biological and Environmental Sciences, University of Stirling, Stirling, Scotland [2] Department of Philosophy, University of Valencia, Valencia, Spain [*] Corresponding author: alexander.duthie@stir.ac.uk [a] Equal contribution'
output:
  pdf_document:
      keep_tex: yes
  html_document:
    df_print: paged
  word_document: default
header-includes:
- \usepackage{fancyhdr}
bibliography: refs.bib
link-citations: yes
linkcolor: blue
biblio-style: apalike
---

We have discovered the fundamental equation that provides a complete description of eco-evolutionary change in any system,

$$\Omega = \sum_{i=1}^{N} \left(\beta_{i} - \delta_{i} + 1 \right)\left(z_{i} + \Delta z_{i} \right).
\tag{1}
$$


In our previous efforts, we derived both the Price equation and the birth-death model from the above.
Here we can derive a fundamental model of community ecology, a discrete time generalised Lotka-Volterra equations leading to modern coexistence theory.
We can do this by partitioning the sum total change $\Omega$ into change caused by density-independent and density-dependent effects,

$$\Omega = \sum_{i=1}^{N} \left(\beta_{i} - \delta_{i} + 1 \right)\left(z_{i} + \Delta z_{i} \right)\left(1 - \sum_{j = 1}^{N}\left(a_{ij}\left(z_{i} + \Delta z_{i} \right) \right) \right).
\tag{2}
$$

In eqn 2, $a_{ij}$ is the effect that $j$ has on the contribution of $i$ to $\Omega$.
Note that we are, again, not relaxing an assumption in eqn 1, nor are we adding something that did not already exist to the model.
Equation 1 is already a complete description of eco-evolutionary change, so it included both density-independent and density-dependent effects. 
The new expression in parentheses is only splitting the total change into density-independent versus density-dependent effects.
As with the previous case of ecology, we can set $z_{i} = 1$ and $\Delta z_{i} = 0$, which allows us to simplify,

$$\Omega = \sum_{i=1}^{N} \left(\beta_{i} - \delta_{i} + 1 \right)\left(1 - \sum_{j = 1}^{N}a_{ij} \right).
\tag{3}
$$

Now, assume that every individual $j$ in the population has an identical effect on $i$, such that $a_{ij} = \alpha$.
With the conceptual understanding that $\alpha$ is then the per capita effect of $j$ on $i$, we can rewrite eqn 3,

$$\Omega = \sum_{i=1}^{N} \left(\beta_{i} - \delta_{i} + 1 \right)\left(1 - \sum_{j = 1}^{N}\alpha \right).
$$


Because we then sum up $\alpha$ a total of $N$ times, it then follows,

$$\Omega = \sum_{i=1}^{N} \left(\beta_{i} - \delta_{i} + 1 \right)\left(1 - \alpha N \right).
$$


Now, we can again assume that individual births ($b = \beta_{i}$) and deaths ($d = \delta_{i}$) are identical for all $i$,

$$\Omega = \sum_{i=1}^{N} \left(b -d + 1 \right)\left(1 - \alpha N \right).
$$


Because we define $\lambda = b - d + 1$,

$$\Omega = \sum_{i=1}^{N} \lambda\left(1 - \alpha N \right).
$$


We now have removed all subscripts $i$ from the right-hand side, and we can rewrite,


$$\Omega =  N \lambda\left(1 - \alpha N \right).
$$

Now is a good time to define $\Omega$ again and add subscripts to $N$,

$$N_{t+1} =  N_{t} \lambda\left(1 - \alpha N_{t} \right).
\tag{4}
$$

Equation 4 gives us a discrete time logistic growth equation. 
This is not typically the way a discrete time equation is expressed, which made me a bit nervous at first, but there is nothing wrong with it either.


We can do some simple simulations to confirm that it behaves as it should.
I am going to make a lot of common simplifying assumptions in what follows (rather, I already have in eqn 4).
I assume that $\alpha$ and $\lambda$ are constant and do not change with density.
Suppose then that we have a population of just two individuals, $N_{t} = 2$. 
With density independent effects, assume that the population is doubling from $t$ to $t + 1$, so $\lambda = 2$.
Now assume that the effect of each individual in the population is to decrease each other individual's growth by $\alpha = 0.01$.
We then have $N_{t+1} =  2 N_{t} \left(1 - 0.01 N_{t} \right)$.
We can simulate this over 10 time steps.

```{r}
NN <- 2;
LL <- 2;
aa <- 0.01;
tt <- 10;
i  <- 1;
while(i < tt){
    Nt        <- NN[i]*LL*(1 - aa * NN[i]);
    NN[i + 1] <- Nt;
    i         <- i + 1;
}
print(NN);
plot(x = 1:10, y = NN, type = "b", pch = 20, lwd = 2,
     xlab = "Time step",
     ylab = "Population density (N)");
points(x = 1:10, y = NN, type = "l", pch = 20, lwd = 2);
```

The population increases exponentially, then levels off at $N = 50$, at which point the population growth $N\lambda = 2(50) = 100$ is balanced by the total effect of competition $\alpha N = 50^{2}(2)(0.01) = 50$, such that $100 - 50$ keeps the population at $50$.

I was a bit bothered by the unusual formulation at first, but now I am feeling better about it.
I am convinced it is correct, albeit not the typically way that researchers tend to model population change.
But usually modellers will switch to continuous time models for logistic growth and generalised Lotka-Volterra. 
And for discrete growth, they will usually do something like $N_{t+1} = N_{t} + N_{t}\lambda(1 - N_{t}/K)$, where $K$ is the carrying capacity.
But this is effort is not derived from first principles, I do not think, in the same way as the above eqn 4.

Recovering proper logistic growth
=======================================

Note that we can also recover a different logistic growth equation if we start at eqn 3, but then assume that $r = b - d$, and density dependent effects only apply to birth and death,

$$\Omega = \sum_{i=1}^{N} \left(r_{i} + 1 \right)\left(1 - \sum_{j = 1}^{N}a_{ij} \right).
\tag{5}
$$


This seems more reasonable.
The effect of an individual $j$ on a focal individual $i$ has to be either on birth or death.
The 1 is a constant, and I do not think it should be affected.
Mathematically, we can expand eqn 5.


$$\Omega = \sum_{i=1}^{N} r_{i}\left(1 - \sum_{j = 1}^{N}a_{ij} \right) + \left(1 - \sum_{j = 1}^{N}a_{ij} \right).$$

Biologically, there is a clear way to resolve this, though I think some caution is needed here with the mathematics.
It is biologically reasonable that $a_{ij} = 0$ in the second term for all $j$.
If $a_{ij}$ only applies to $r_{i}$ such that $a_{ij} = 0$ for all $i$ and $j$ in the second term, then,

$$\Omega = \sum_{i=1}^{N} r_{i}\left(1 - \sum_{j = 1}^{N}a_{ij} \right) + 1.$$

If we can get to this point, then we can make the same assumption that we did around eqn 3, such that every individual $j$ has an identical effect on $i$, so $a_{ij} = \alpha$.
It then follows,

$$\Omega = \sum_{i=1}^{N} r_{i}\left(1 - \sum_{j = 1}^{N}\alpha \right) + 1.$$

From here, we then sum up the $\alpha$ values,

$$\Omega = \sum_{i=1}^{N} r_{i}\left(1 - \alpha N \right) + 1.$$

If we assume that $r_{i} = r$ for all $i$, then we are also summing $r(1 - \alpha N) + 1$ a total of $N$ times,


$$\Omega = N \left( r_{i}\left(1 - \alpha N \right) + 1\right).$$

By setting $\Omega = N_{t+1}$ and $N = N_{t}$, we can then recover,

$$N_{t+1} = N_{t} + rN_{t}\left(1 - \alpha N_{t}\right)$$

Again, in this case, $\alpha$ reflects interactions among individuals only affecting birth and death.
This is a standard discrete time generalised Lotka-Volterra equation, as appears in @Chesson2000b.
To recover community ecology, it should be a standard matter of defining two sets $J$ and $K$ representing different species,

$$\Omega = \sum_{i=1}^{N} \left(r_{i} + 1 \right)\left(1 - \sum_{j \in J}a_{ij} - \sum_{k \in K}a_{ik} \right).$$

Summations can be made over different scales too, but I think that this gets us solidly to @Chesson2000b.




**IDEAS**

Do we have an issue because *only* a trait of j's should affect both i's contribution to the sum population size and the sum trait quantity omega, right? The existence of j shouldn't matter, unless we're multiplying 1 by j's trait. But we shouldn't double count j's existence and its trait value to predict how it affects i (or anything about i).

Or maybe the original formula isn't quite right. We need alpha to actually be imaginary. So maybe if we have 0 + i\alpha_{ij}, something like $(0 + i1)\alpha * (i\tau_{ij})$

Well, could try to have an individual with the property $(1 + 0.5i)$ and define ($\alpha = 1 + 0.1i$, but something seems off here. Then again, if we have fitness as 2, then set an individual and trait to $(1 + 0.5i)$, affected by competition of a j individual, $a_{ij} = (0 + 0.5i)$. I'm not sure. I can't get the density to change while also getting the trait to change. Unless it's something like $z = 1 + 0.5i$, then $a_{ij} = (0 + 0.1i)$, so $z + za$.

One last try before bed, if w = 2, let's say, $2 (1 + 0.5i) * (1 - (0 - 0i) * (1 + 0.4i))$, where $\alpha = (0 - 0i)$ and j is $(1 + 0.4i)$. But alpha is the effect of a *trait* on fitness, so something isn't quite right here.


Okay, try making a_{ij} into an imaginary number. This should work.


Deriving Price like
=====================

$$\frac{\Omega}{N} = \underbrace{\mathbb{E}[w z]}_{\text{Term 1}} + \underbrace{\mathbb{E}[w \Delta z]}_{\text{Term 2}} - \underbrace{\mathbb{E}\left[w \sum_{j=1}^N a_{ij} z_i^2 \right]}_{\text{Term 3}} - \underbrace{\mathbb{E}\left[w \sum_{j=1}^N \left( 2 a_{ij} z_i \Delta z_i + a_{ij} (\Delta z_i)^2 \right) \right]}_{\text{Term 4}}.$$

Then,

$$\bar{w} \bar{z}' = \underbrace{\text{Cov}(w, z) + \bar{w} \bar{z}}_{\text{Term 1}} + \underbrace{\mathbb{E}[w \Delta z]}_{\text{Term 2}} - \underbrace{\mathbb{E}\left[w \sum_{j=1}^N a_{ij} z_i^2 \right]}_{\text{Term 3}} - \underbrace{\mathbb{E}\left[w \sum_{j=1}^N \left( 2 a_{ij} z_i \Delta z_i + a_{ij} (\Delta z_i)^2 \right) \right]}_{\text{Term 4}}.$$

Then,

$$\bar{w} \Delta \bar{z} = \text{Cov}(w, z) + \mathbb{E}[w \Delta z] - \mathbb{E}\left[w \sum_{j=1}^N a_{ij} z_i^2 \right] - \mathbb{E}\left[w \sum_{j=1}^N \left( 2 a_{ij} z_i \Delta z_i + a_{ij} (\Delta z_i)^2 \right) \right].$$
If we are willing to assume that all individuals $j$ have the same effect on a focal $i$, then we can rewrite as,

$\bar{w} \Delta \bar{z} = \text{Cov}(w, z) + \mathbb{E}[w \Delta z] - N \mathbb{E}[w \alpha_i z_i^2] - N \mathbb{E}\left[w \alpha_i \left( 2 z_i \Delta z_i + (\Delta z_i)^2 \right) \right].$



This simplifies again,

$$\begin{align*}
\bar{w} \Delta \bar{z} &= \text{Cov}(w, z) + \mathbb{E}[w \Delta z] - N \mathbb{E}\left[ w \alpha_i \left( z_i^2 + 2 z_i \Delta z_i + (\Delta z_i)^2 \right) \right] \\
&= \text{Cov}(w, z) + \mathbb{E}[w \Delta z] - N \mathbb{E}\left[ w \alpha_i (z_i + \Delta z_i)^2 \right].
\end{align*}$$


$$\bar{w} \Delta \bar{z} = \text{Cov}(w, z) + \mathbb{E}[w \Delta z] - N \mathbb{E}\left[ w \alpha_i (z_i + \Delta z_i)^2 \right].$$
Let's assume that $\Delta z_{i} = 0$, where the middle term will drop out and we can focus on population level effects on trait change (selection and drift) and the effect of interaction coefficients,

$$\bar{w} \Delta \bar{z} = \text{Cov}(w, z) - N \mathbb{E}[w \alpha_i z_i^2].$$

Let's just drop the subscripts in the second term as in the first,

$$\bar{w} \Delta \bar{z} = \text{Cov}(w, z) - N \mathbb{E}[w \alpha z^2].$$

It's reassuring that the sign of z doesn't affect the second term. Verbally, 
I *think* the first term represents the change in a trait attributable to selection (and drift) in the absence of interspecific interactions, while the second term represents trait change attributable to selection attributable to interactions? 

Note that the second term is the expected interaction between fitness and interaction strength $w \alpha$ times $z^2$, which embeds the variance of $z^{2}$ because,

$$E[z_{i}^{2}] = Var(z) + \bar{z}^{2}$$




References 
==========================


























